//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class cabecera_reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cabecera_reserva()
        {
            this.detalle_reserva = new HashSet<detalle_reserva>();
        }
    
        public int id_reserva { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_reserva { get; set; }
        public Nullable<System.DateTime> fecha_entrada { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public Nullable<int> estado_reserva { get; set; }
        public string observaciones { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_reserva> detalle_reserva { get; set; }
    }
}
