//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public habitacion()
        {
            this.detalle_reserva = new HashSet<detalle_reserva>();
        }
    
        public int id_habitacion { get; set; }
        public Nullable<int> numero_habitacion { get; set; }
        public Nullable<int> piso_habitacion { get; set; }
        public Nullable<double> preciodiario_habitacion { get; set; }
        public string tipo_habitacion { get; set; }
        public string caracteristicas_habitacion { get; set; }
        public Nullable<int> estado_habitacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_reserva> detalle_reserva { get; set; }
    }
}
